### PR TITLE
Add support for SSL client cert.

### PR DESCRIPTION
**Pull request by laurentluce**
``` shell
$ ./wrk | grep ssl-c
    -C, --ssl-c-cert  <S>  SSL client certificate     
    -K, --ssl-c-key   <S>  SSL client private key

$ ./wrk -c1 -t1 -d1 --ssl-c-cert cert.pem --ssl-c-key private_key.pem https://localhost/test
```

### CODE REVIEW

**Comment by aidylewis** [comment]
Is there any reason why this has not been merged?

**Comment by knasim** [comment]
@aidylewis  - yes ! why wasn't the ever merged.  nice work @laurentluce !

**Comment by knasim** [comment]
doesn't seem to make the TLS connection.

**Comment by sanderdekoning** [comment]
Can someone merge this please?

**Comment by aidylewis** [comment]
This would also be a big win for us at the BBC.

**Comment by sanderdekoning** [comment]
@aidylewis also see https://github.com/wg/wrk/pull/302

**Comment by laurentluce** [comment]
Closing this PR since similar work is tracked in #302

**Pull request closed without merging**
